version: 0.1

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on 'date'
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/my-cicd-java-aws-app*/*
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'